package pojos;
// Generated Dec 24, 2020 3:32:06 AM by Hibernate Tools 4.3.1



/**
 * Chats generated by hbm2java
 */
public class Chats  implements java.io.Serializable {


     private Integer id;
     private String name;
     private byte[] chatFile;

    public Chats() {
    }

    public Chats(String name, byte[] chatFile) {
       this.name = name;
       this.chatFile = chatFile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getChatFile() {
        return this.chatFile;
    }
    
    public void setChatFile(byte[] chatFile) {
        this.chatFile = chatFile;
    }




}


