package pojos;
// Generated Dec 24, 2020 3:32:06 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userName;
     private String nickName;
     private String email;
     private String password;
     private byte[] image;

    public User() {
    }

    public User(String userName, String nickName, String email, String password, byte[] image) {
       this.userName = userName;
       this.nickName = nickName;
       this.email = email;
       this.password = password;
       this.image = image;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


